data_path: "./data/processed/anthropic/anthropic_harmless_base_train_10000canonrand_balanced.csv"
data_len: 5000
alg_model: "openai/gpt-4o-mini-2024-07-18"
s0_skip_principle_generation: true
s0_added_standard_principles_to_test:
  - v2
annotator:
  skip: true