data_path: "./data/processed/synthetic/synthetic_data_orthogonal_adcbg.csv"
alg_model: openai/gpt-3.5-turbo-0125
s2_num_clusters: 40
s1_num_principles_per_instance: 10
s1_num_rankings_per_sampling_step: 5 # ablation: IMPORTANT DIFFERENCE
s3_max_principles: 5
annotator:
  is_single_annotator: true
  base_constitutional_annotator_configs:
    - data/annotator_configs/chatgpt_fn_constitutional_base_neutral_v1
    - data/annotator_configs/gpt4o_fn_constitutional_base_neutral_v1
  other_annotator_configs:
    - data/annotator_configs/chatgpt_fn_noinstruction
    - data/annotator_configs/alpaca_eval_gpt4o_fn_noinstruction
alg_prompts:
  generator_prompts:
  - '<|im_start|>system

    Your job is to analyse data and come up with explanations. You''re an expert at
    this.

    <|im_end|>

    <|im_start|>user

    {rankings}

    Given the data above, why do you think the annotator selected the given samples
    over the other samples? Reply with {num_principles} most likely rules that may
    explain the selections, each in 10 words or less. Be specific and focus on the
    differences between the pairs, for example in content, subjects, traits,
    writing style or topic.

    Note: the intend of the selection was to find bad samples (to prevent a user seeing
    them). Always suggest as rule that starts with ''Select the response that...<bad
    thing>''. Suggest rules that help find bad samples.


    Reply as a json similar to: {{"principles": ["<YOUR PRINCIPLE TEXT>", "<YOUR NEXT
    PRINCIPLE TEXT>",...]}}.

    DO NOT respond with any text apart from the json format above!

    DO NOT add markdown formatting around JSON.

    ONLY REPLY IN JSON FORMAT

    <|im_end|>'
  - '<|im_start|>system

    Your job is to analyse data and come up with explanations. You''re an expert at
    this.

    <|im_end|>

    <|im_start|>user

    {rankings}


    Given the data above, why do you think the annotator selected the given samples
    over the other samples? Reply with {num_principles} most likely rules that may
    explain the selections, each in 10 words or less. Be specific and focus on the
    differences between the pairs, for example in content, subjects, traits,
    writing style or topic.  Always suggest as rule that starts with ''Select the
    response that...''.


    Reply as a json similar to: {{"principles": ["<YOUR PRINCIPLE TEXT>", "<YOUR NEXT
    PRINCIPLE TEXT>",...]}}.

    DO NOT respond with any text apart from the json format above!

    DO NOT add markdown formatting around JSON.

    ONLY REPLY IN JSON FORMAT

    <|im_end|>'