data_path: "./data/processed/tatsu_lab/alpacaeval_goldcrossannotations_rand.csv"
data_invert_labels: true # IMPORTANT DIFFERENCE
data_len: 65
test_data_path: "./data/processed/tatsu_lab/alpacaeval_goldcrossannotations_rand.csv"
test_data_start_index: 200
test_data_len: 65
test_data_invert_labels: true
alg_model: "openai/gpt-4o-2024-05-13"
s1_num_principles_per_instance: 2
s2_num_clusters: 80
s3_max_principles: 5
generate_constitution: false
annotator:
  is_single_annotator: true
  base_constitutional_annotator_configs:
    - data/annotator_configs/claude_3_opus_ranking_constitutional_base_neutral_v1
    - data/annotator_configs/claude_3_haiku_ranking_constitutional_base_neutral_v1
    - data/annotator_configs/chatgpt_fn_constitutional_base_neutral_v1
    - data/annotator_configs/gpt4o_fn_constitutional_base_neutral_v1
  other_annotator_configs:
    - data/annotator_configs/claude_3_opus_ranking_noinstruction
    - data/annotator_configs/claude_3_haiku_ranking_noinstruction
    - data/annotator_configs/chatgpt_fn_noinstruction
    - data/annotator_configs/alpaca_eval_gpt4o_fn_noinstruction
  constitution: "1. Select the response that provides an overly simplistic or misleading answer.\n2. Select the response that lacks depth in analysis.\n3. Select the response that contains incorrect or nonsensical logic.\n4. Select the response that lists all entities in the text.\n5. Select the response that ends abruptly without a conclusion."
  test_data_only: true
